//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVPlayerWardrobe.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVPlayerWardrobe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index,0 [0x5][0xbc],1 [0x19][0xef],2 [0x7][0x0],3 [0x7][0x4],4 [0x7][0x8],5 [0x7][0xc],6 [0x7][0x10],7 [0x7][0x14],8 [0x7][0x18],9 [0x7][0x1c],10 [0x7][0x20],11 [0x7][0x24],12 [0x7][0x28],13 [0x7][0x2c],14 [0x7][0x30],15 [0x7][0x34],16 [0x7][0x38],17 [0x7][0x3c],18 [0x7][0x40],19 [0x7][0x44],20 [0x7][0x48],21 [0x7][0x4c],22 [0x7][0x50],23 [0x7][0x54],24 [0x7][0x58],25 [0x7][0x5c],26 [0x7][0x60],27 [0x7][0x64],28 [0x7][0x68],29 [0x7][0x6c],30 [0x7][0x70],31 [0x7][0x74],32 [0x7][0x78],33 [0x7][0x7c],34 [0x9][ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string enpcbase_exh {
            get {
                return ResourceManager.GetString("enpcbase_exh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index,0 [0x0][0x0],1 [0x2][0xc],2 [0x0][0x4],3 [0x2][0xd],4 [0x2][0xe],5 [0x2][0xf],6 [0x2][0x10],7 [0x2][0x11],8 [0x0][0x8],9 [0x3][0x14],10 [0x19][0x15]
        ///1000000,&quot;&quot;,0,&quot;&quot;,0,0,1,0,0,&quot;&quot;,3,false
        ///1000001,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0,&quot;&quot;,0,false
        ///1000002,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0,&quot;&quot;,0,false
        ///1000003,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0,&quot;&quot;,0,false
        ///1000004,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0,&quot;&quot;,0,false
        ///1000005,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0,&quot;&quot;,0,false
        ///1000006,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0,&quot;&quot;,0,false
        ///1000007,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0,&quot;&quot;,0,false
        ///1000008,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0,&quot;&quot;,0,false
        ///1000009,&quot;&quot;,0,&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string enpcresident_exh_en {
            get {
                return ResourceManager.GetString("enpcresident_exh_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index,0 [0x0][0x0],1 [0x2][0x10],2 [0x0][0x4],3 [0x2][0x11],4 [0x2][0x12],5 [0x2][0x13],6 [0x2][0x14],7 [0x2][0x15],8 [0x0][0x8],9 [0x0][0xc],10 [0x5][0x80],11 [0x5][0x82],12 [0x3][0x8e],13 [0x3][0x8f],14 [0x7][0x68],15 [0x3][0x90],16 [0x3][0x91],17 [0x3][0x92],18 [0x5][0x84],19 [0x7][0x6c],20 [0x19][0x95],21 [0x1a][0x95],22 [0x1b][0x95],23 [0x1c][0x95],24 [0x7][0x70],25 [0x7][0x74],26 [0x1d][0x95],27 [0x1e][0x95],28 [0x1f][0x95],29 [0x5][0x86],30 [0x3][0x93],31 [0x5][0x88],32 [0x3][0x94],33 [0x6][0x78],34  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string item_exh_en {
            get {
                return ResourceManager.GetString("item_exh_en", resourceCulture);
            }
        }
    }
}
